### ISSUE TITLE
Couldn't create an emulator

### ISSUE THREAD

**Issue by 0v3rt1r3d** [gojuno/swarmer#35]
I tried to create an emulator with shortest list of parameters and got the input.
```
[Fri Oct 27 21:32:33 MSK 2017]: Already running emulators: []
[Fri Oct 27 21:32:33 MSK 2017]: Creating avd «emulator1».
[Fri Oct 27 21:32:33 MSK 2017]: Error during creation of avd «emulator1», error = java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

[Fri Oct 27 21:32:33 MSK 2017]: Error during creation of avd «emulator1», error = java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

[Fri Oct 27 21:32:33 MSK 2017]: Error during creation of avd «emulator1», error = java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

[Fri Oct 27 21:32:34 MSK 2017]: Error during creation of avd «emulator1», error = java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

[Fri Oct 27 21:32:34 MSK 2017]: Could not create avd «emulator1», error = java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

Exception in thread "main" java.lang.IllegalStateException: Process [/Users/overtired/Library/Android/sdk/tools/bin/avdmanager, create, avd, --force, --name, «emulator1», --package, system-images;android-25;google_apis;x86, --abi, google_apis/x86] exited with non-zero code 1 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt:100)
	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:72)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10346)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

The script for swarmer was ...

```
#!/bin/bash
java -jar /correctPathToSwarmer/swarmer.jar start \
--emulator-name «emulator1» \
--package "system-images;android-25;google_apis;x86" \
--android-abi google_apis/x86 \
--path-to-config-ini emulator1.ini
```
What may be wrong?

**Comment by artem-zinnatullin** [comment]
@0v3rt1r3d can you please paste output of `java -version`? 

I suspect you have JDK9 installed which is not super compatible with Android tooling

**Comment by 0v3rt1r3d** [comment]
Thank you! I had installed java9. Changing to 8 version solved my problem:)

**Comment by artem-zinnatullin** [comment]
@0v3rt1r3d nice! 

It was pure coincidence that couple minutes before checking your issue I've spent some time on fixing exact same JDK9 issue in other project haha
